import { Link } from "react-router-dom";
import Navbar from "../../components/common/Navbar";
import Footer from "../../components/common/Footer";
import { useLanguage } from "../../context/LanguageContext";

const Icon=({type})=><span className="feature-icon" aria-hidden="true">{{home:"⌂",tuition:"⌁",market:"◫"}[type]}</span>;
export default function Landing(){const {t}=useLanguage(); const cards=[
  ["home",t("Find Home / Mess"),t("Find your next home, not just a room."),t("Browse mess seats and home listings by location, budget and availability."),t("Explore homes"),"lavender"],
  ["tuition",t("Tuition"),t("Find the right tuition opportunity."),t("Students can discover tuition posts while guardians connect with suitable tutors."),t("Explore tuition"),"mint"],
  ["market",t("Buy / Sell"),t("Buy and sell what you need."),t("Discover useful items from your campus community or post your own products for sale."),t("Explore marketplace"),"peach"]
]; return <div className="page-shell"><Navbar/><main>
  <section className="hero"><div className="hero-copy"><p className="kicker">✦ &nbsp; {t("Built around student life")}</p><h1>{t("Your next chapter")}<br/>{t("starts closer than")}<br/>{t("you think.")}</h1><p>{t("One trusted place to find a home or mess, connect through tuition, and buy or sell useful items—made for the university community.")}</p><div className="hero-actions"><a className="button button-primary" href="#features">{t("Start exploring")} <span>→</span></a><Link className="text-link" to="/login?mode=signup">{t("I want to post something")} ↗</Link></div><div className="trust-row"><div className="avatars"><span>SA</span><span>NR</span><span>MI</span><span>+2k</span></div><p><strong>{t("Growing every day")}</strong><br/>{t("with students in Khulna")}</p></div></div>
  <div className="hero-visual"><div className="orb one"/><div className="orb two"/><div className="listing-card"><div className="room-art"><div className="window">┼</div><div className="plant">♧</div><div className="bed"/></div><div className="listing-copy"><span>● &nbsp; {t("2 seats available")}</span><strong>{t("Sonadanga, Khulna")}</strong><small>{t("Tk 3,500 / month")}</small></div></div><div className="float-card verified"><b>✓</b><span><strong>{t("Verified profiles")}</strong><small>{t("Connect with confidence")}</small></span></div><div className="float-card match"><b>RK</b><span><strong>{t("New tuition match!")}</strong><small>{t("Class 9 · Mathematics")}</small></span></div><i className="spark">✦</i></div></section>
  <section className="intro" id="features"><div><p className="kicker">{t("One nest. Three possibilities.")}</p><h2>{t("Everything you need to")}<br/><em>{t("move forward.")}</em></h2></div><p>{t("Find a home or mess, connect through tuition, and buy or sell useful items—all in one trusted student platform.")}</p></section>
  <section className="card-grid">{cards.map((c,i)=><article className={`path-card ${c[5]}`} id={c[0]} key={c[1]}><div className="card-top"><Icon type={c[0]}/><span>0{i+1}</span></div><p className="card-label">{c[1]}</p><h3>{c[2]}</h3><p>{c[3]}</p><Link to="/login?mode=signup">{c[4]} <span>→</span></Link></article>)}</section>
  <section className="community-strip" id="community"><div className="community-copy"><p className="kicker">{t("Made for your campus")}</p><h2>{t("A simpler way to find")}<br/>{t("what matters.")}</h2><p>{t("Verified profiles, useful filters and direct conversations bring every part of student life into one calm, trusted space.")}</p></div><div className="community-stats"><div><strong>4</strong><span>{t("User communities")}</span></div><div><strong>3</strong><span>{t("Needs, one platform")}</span></div><div><strong>100%</strong><span>{t("Free to get started")}</span></div></div></section>
  <section className="final-cta"><i>✦</i><p className="kicker">{t("Your campus. Your community.")}</p><h2>{t("Ready to find your place?")}</h2><p>{t("Join CampusNest today. Browsing, posting and applying are always free.")}</p><div><Link className="button button-dark" to="/login?mode=signup">{t("Get started for free")} →</Link><Link className="text-link" to="/login">{t("Already a member? Log in")}</Link></div></section>
  </main><Footer/></div>}
