import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Navbar from "../../components/common/Navbar";
import Footer from "../../components/common/Footer";
import { useLanguage } from "../../context/LanguageContext";
import { publicRequest } from "../../lib/api";

const Icon=({type})=><span className="feature-icon" aria-hidden="true">{{home:"⌂",tuition:"⌁",market:"◫"}[type]}</span>;
export default function Landing(){const {t}=useLanguage(); const [community, setCommunity]=useState({students:null,guardians:null,homeowners:null}); useEffect(()=>{publicRequest("/stats/community").then(setCommunity).catch(()=>{});},[]); const count=(value)=>value===null?"—":value.toLocaleString(); const cards=[
  ["home",t("Find Home / Mess"),t("Find your next home, not just a room."),t("Browse mess seats and home listings by location, budget and availability."),t("Explore homes"),"lavender"],
  ["tuition",t("Tuition"),t("Find the right tuition opportunity."),t("Students can discover tuition posts while guardians connect with suitable tutors."),t("Explore tuition"),"mint"],
  ["market",t("Buy / Sell"),t("Buy and sell what you need."),t("Discover useful items from your campus community or post your own products for sale."),t("Explore marketplace"),"peach"]
]; return <div className="page-shell"><Navbar/><main>
  <section className="hero"><div className="hero-copy"><div className="welcome-chip"><span>✦</span>{t("Welcome to CampusNest")}</div><h1>{t("Everything student life needs,")}<br/><em>{t("all in one place.")}</em></h1><p>{t("Find a safe home, discover tuition opportunities and connect with your university community through one simple, trusted platform.")}</p><div className="hero-actions"><a className="button button-primary" href="#features">{t("Explore CampusNest")} <span>→</span></a><Link className="text-link" to="/login?mode=signup">{t("Join our community")} ↗</Link></div><div className="trust-row"><div className="avatars"><span>SA</span><span>NR</span><span>MI</span><span>+2k</span></div><p><strong>{t("Built for students, families and homeowners")}</strong><br/>{t("A growing community in Khulna")}</p></div></div>
  <div className="hero-visual"><div className="orb one"/><div className="orb two"/><div className="listing-card"><div className="room-art"><div className="window">┼</div><div className="plant">♧</div><div className="bed"/></div><div className="listing-copy"><span>● &nbsp; {t("2 seats available")}</span><strong>{t("Sonadanga, Khulna")}</strong><small>{t("Tk 3,500 / month")}</small></div></div><div className="float-card verified"><b>✓</b><span><strong>{t("Verified profiles")}</strong><small>{t("Connect with confidence")}</small></span></div><div className="float-card match"><b>RK</b><span><strong>{t("New tuition match!")}</strong><small>{t("Class 9 · Mathematics")}</small></span></div><i className="spark">✦</i></div></section>
  <section className="intro" id="features"><div><p className="kicker">{t("One nest. Three possibilities.")}</p><h2>{t("Everything you need to")}<br/><em>{t("move forward.")}</em></h2></div><p>{t("Find a home or mess, connect through tuition, and buy or sell useful items—all in one trusted student platform.")}</p></section>
  <section className="card-grid">{cards.map((c,i)=><article className={`path-card ${c[5]}`} id={c[0]} key={c[1]}><div className="card-top"><Icon type={c[0]}/><span>0{i+1}</span></div><p className="card-label">{c[1]}</p><h3>{c[2]}</h3><p>{c[3]}</p><Link to="/login?mode=signup">{c[4]} <span>→</span></Link></article>)}</section>
  <section className="community-strip" id="community"><div className="community-copy"><p className="kicker">{t("Made for your campus")}</p><h2>{t("A community that")}<br/>{t("keeps growing.")}</h2><p>{t("Real people are joining CampusNest to find homes, share tuition opportunities and build a more connected university community.")}</p></div><div className="community-stats"><div><i>♙</i><strong>{count(community.students)}</strong><span>{t("Students joined")}</span></div><div><i>♡</i><strong>{count(community.guardians)}</strong><span>{t("Guardians joined")}</span></div><div><i>⌂</i><strong>{count(community.homeowners)}</strong><span>{t("Homeowners joined")}</span></div></div></section>
  <section className="final-cta"><i>✦</i><p className="kicker">{t("Your campus. Your community.")}</p><h2>{t("Ready to find your place?")}</h2><p>{t("Join CampusNest today. Browsing, posting and applying are always free.")}</p><div><Link className="button button-dark" to="/login?mode=signup">{t("Get started for free")} →</Link><Link className="text-link" to="/login">{t("Already a member? Log in")}</Link></div></section>
  </main><Footer/></div>}
