import { Link } from "react-router-dom";
import Navbar from "../../components/common/Navbar";
import Footer from "../../components/common/Footer";

const Icon=({type})=><span className="feature-icon" aria-hidden="true">{{home:"⌂",work:"◫",tutor:"⌁"}[type]}</span>;
const cards=[
  ["home","Accommodation","Find your next home, not just a room.","Browse mess seats and basa listings by location, budget and availability.","Explore homes","lavender"],
  ["work","Student opportunities","Turn spare hours into real experience.","Discover part-time work and tuition leads shared by your student community.","Browse opportunities","mint"],
  ["tutor","For guardians","Meet the tutor your child needs.","Post your exact requirements and review suitable teacher profiles in one place.","Find a tutor","peach"]
];
export default function Landing(){return <div className="page-shell"><Navbar/><main>
  <section className="hero"><div className="hero-copy"><p className="kicker">✦ &nbsp; Built around student life</p><h1>Your next chapter<br/>starts <em>closer</em> than<br/>you think.</h1><p>One trusted place to find a home, discover flexible work, and connect with the right tutor—made for the university community.</p><div className="hero-actions"><a className="button button-primary" href="#homes">Start exploring <span>→</span></a><Link className="text-link" to="/login?mode=signup">I want to post something ↗</Link></div><div className="trust-row"><div className="avatars"><span>SA</span><span>NR</span><span>MI</span><span>+2k</span></div><p><strong>Growing every day</strong><br/>with students in Khulna</p></div></div>
  <div className="hero-visual"><div className="orb one"/><div className="orb two"/><div className="listing-card"><div className="room-art"><div className="window">┼</div><div className="plant">♧</div><div className="bed"/></div><div className="listing-copy"><span>● &nbsp; 2 seats available</span><strong>Sonadanga, Khulna</strong><small>Tk 3,500 / month</small></div></div><div className="float-card verified"><b>✓</b><span><strong>Verified profiles</strong><small>Connect with confidence</small></span></div><div className="float-card match"><b>RK</b><span><strong>New tuition match!</strong><small>Class 9 · Mathematics</small></span></div><i className="spark">✦</i></div></section>
  <section className="intro" id="homes"><div><p className="kicker">One nest. Many possibilities.</p><h2>Everything you need to<br/><em>move forward.</em></h2></div><p>From a safe room near campus to the opportunity that fits between classes, CampusNest brings the scattered pieces together.</p></section>
  <section className="card-grid" id="opportunities">{cards.map((c,i)=><article className={`path-card ${c[5]}`} key={c[1]}><div className="card-top"><Icon type={c[0]}/><span>0{i+1}</span></div><p className="card-label">{c[1]}</p><h3>{c[2]}</h3><p>{c[3]}</p><Link to="/login?mode=signup">{c[4]} <span>→</span></Link></article>)}</section>
  <section className="community-strip" id="community"><div className="community-copy"><p className="kicker">Made for your campus</p><h2>A simpler way to find<br/>what matters.</h2><p>Verified profiles, useful filters and direct conversations bring every part of student life into one calm, trusted space.</p></div><div className="community-stats"><div><strong>4</strong><span>User communities</span></div><div><strong>3</strong><span>Needs, one platform</span></div><div><strong>100%</strong><span>Free to get started</span></div></div></section>
  <section className="final-cta"><i>✦</i><p className="kicker">Your campus. Your community.</p><h2>Ready to find your place?</h2><p>Join CampusNest today. Browsing, posting and applying are always free.</p><div><Link className="button button-dark" to="/login?mode=signup">Get started for free →</Link><Link className="text-link" to="/login">Already a member? Log in</Link></div></section>
  </main><Footer/></div>}
