/* oxlint-disable react/only-export-components -- provider and its hook share one context */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const bangla = {
  "Find Home/Mess": "বাসা/মেস খুঁজুন", "Find Tuition": "টিউশন খুঁজুন", "Buy/Sell": "কেনা/বেচা", "My profile": "আমার প্রোফাইল", "Log out": "লগ আউট", "Log in": "লগ ইন", "Join CampusNest": "CampusNest-এ যোগ দিন",
  "A trusted place for every part of student life.": "শিক্ষার্থী জীবনের প্রতিটি প্রয়োজনের বিশ্বস্ত ঠিকানা।", "Find a home": "বাসা খুঁজুন", "Opportunities": "সুযোগসমূহ", "Khulna University": "খুলনা বিশ্ববিদ্যালয়",
  "Built around student life": "শিক্ষার্থী জীবনকে ঘিরে", "Your next chapter": "তোমার নতুন অধ্যায়", "starts closer than": "শুরু হোক আরও কাছে", "you think.": "যতটা তুমি ভাবো।", "One trusted place to find a home or mess, connect through tuition, and buy or sell useful items—made for the university community.": "বাসা বা মেস খোঁজা, টিউশনের মাধ্যমে যুক্ত হওয়া এবং দরকারি জিনিস কেনাবেচার এক বিশ্বস্ত জায়গা—বিশ্ববিদ্যালয় কমিউনিটির জন্য।", "Start exploring": "খোঁজা শুরু করুন", "I want to post something": "আমি কিছু পোস্ট করতে চাই", "Growing every day": "প্রতিদিন বড় হচ্ছে", "with students in Khulna": "খুলনার শিক্ষার্থীদের সঙ্গে", "2 seats available": "২টি সিট খালি", "Sonadanga, Khulna": "সোনাডাঙ্গা, খুলনা", "Tk 3,500 / month": "মাসে ৩,৫০০ টাকা", "Verified profiles": "যাচাইকৃত প্রোফাইল", "Connect with confidence": "নির্ভয়ে যোগাযোগ করুন", "New tuition match!": "নতুন টিউশন মিলেছে!", "Class 9 · Mathematics": "নবম শ্রেণি · গণিত",
  "One nest. Three possibilities.": "এক নীড়ে তিন সম্ভাবনা।", "Everything you need to": "আপনার প্রয়োজনীয় সবকিছু", "move forward.": "এগিয়ে যাওয়ার জন্য।", "Find a home or mess, connect through tuition, and buy or sell useful items—all in one trusted student platform.": "বাসা বা মেস, টিউশন এবং দরকারি জিনিস কেনাবেচা—সব এক বিশ্বস্ত শিক্ষার্থী প্ল্যাটফর্মে।", "Find Home / Mess": "বাসা / মেস খুঁজুন", "Find your next home, not just a room.": "শুধু ঘর নয়, খুঁজে নিন আপনার পরবর্তী ঠিকানা।", "Browse mess seats and home listings by location, budget and availability.": "এলাকা, বাজেট ও খালি সিট অনুযায়ী মেস ও বাসার তালিকা দেখুন।", "Explore homes": "বাসা দেখুন", "Tuition": "টিউশন", "Find the right tuition opportunity.": "সঠিক টিউশনের সুযোগ খুঁজুন।", "Students can discover tuition posts while guardians connect with suitable tutors.": "শিক্ষার্থীরা টিউশন খুঁজবে এবং অভিভাবকেরা উপযুক্ত শিক্ষক পাবেন।", "Explore tuition": "টিউশন দেখুন", "Buy / Sell": "কেনা / বেচা", "Buy and sell what you need.": "প্রয়োজনীয় জিনিস কিনুন ও বিক্রি করুন।", "Discover useful items from your campus community or post your own products for sale.": "ক্যাম্পাস কমিউনিটি থেকে দরকারি জিনিস খুঁজুন বা নিজের পণ্য বিক্রি করুন।", "Explore marketplace": "মার্কেটপ্লেস দেখুন", "Made for your campus": "আপনার ক্যাম্পাসের জন্য", "A simpler way to find": "প্রয়োজনীয় জিনিস খোঁজার", "what matters.": "সহজ উপায়।", "Verified profiles, useful filters and direct conversations bring every part of student life into one calm, trusted space.": "যাচাইকৃত প্রোফাইল, প্রয়োজনীয় ফিল্টার ও সরাসরি কথোপকথন শিক্ষার্থী জীবনের সবকিছু এক বিশ্বস্ত জায়গায় আনে।", "User communities": "ধরনের ব্যবহারকারী", "Needs, one platform": "প্রয়োজন, এক প্ল্যাটফর্ম", "Free to get started": "শুরু করা সম্পূর্ণ ফ্রি", "Your campus. Your community.": "আপনার ক্যাম্পাস, আপনার কমিউনিটি।", "Ready to find your place?": "নিজের জায়গা খুঁজতে প্রস্তুত?", "Join CampusNest today. Browsing, posting and applying are always free.": "আজই CampusNest-এ যোগ দিন। দেখা, পোস্ট করা ও আবেদন সবসময় ফ্রি।", "Get started for free": "বিনামূল্যে শুরু করুন", "Already a member? Log in": "আগেই সদস্য? লগ ইন করুন",
  "Back to home": "হোমে ফিরুন", "Join the community": "কমিউনিটিতে যোগ দিন", "Welcome back": "আবার স্বাগতম", "Create your nest.": "আপনার নীড় তৈরি করুন।", "Good to see you.": "আপনাকে আবার দেখে ভালো লাগছে।", "Choose your role and join CampusNest.": "আপনার ভূমিকা বেছে নিয়ে CampusNest-এ যোগ দিন।", "Log in to continue to your account.": "অ্যাকাউন্টে যেতে লগ ইন করুন।", "Full name": "পুরো নাম", "Your full name": "আপনার পুরো নাম", "I am joining as": "আমি যোগ দিচ্ছি", "Student": "শিক্ষার্থী", "Guardian": "অভিভাবক", "Home / mess owner": "বাসা / মেস মালিক", "Admin (approved emails only)": "অ্যাডমিন (শুধু অনুমোদিত ইমেইল)", "Email address": "ইমেইল ঠিকানা", "Password": "পাসওয়ার্ড", "At least 6 characters": "কমপক্ষে ৬ অক্ষর", "Hide": "লুকান", "Show": "দেখান", "Remember me": "আমাকে মনে রাখুন", "Forgot password?": "পাসওয়ার্ড ভুলে গেছেন?", "Please wait...": "অপেক্ষা করুন...", "Create free account": "ফ্রি অ্যাকাউন্ট তৈরি করুন", "Already have an account?": "আগেই অ্যাকাউন্ট আছে?", "New to CampusNest?": "CampusNest-এ নতুন?", "Create an account": "অ্যাকাউন্ট তৈরি করুন", "Finding a safe place near campus shouldn’t feel like a full-time job.": "ক্যাম্পাসের কাছে নিরাপদ জায়গা খোঁজা কঠিন কাজ হওয়া উচিত নয়।", "CampusNest brings the right people closer.": "CampusNest সঠিক মানুষদের কাছে আনে।", "Made for the university community": "বিশ্ববিদ্যালয় কমিউনিটির জন্য তৈরি",
  "SIGNED IN": "লগ ইন করা হয়েছে", "Welcome, {name}": "স্বাগতম, {name}", "ACCOUNT": "অ্যাকাউন্ট", "QUICK ACTIONS": "দ্রুত কাজ", "What would you like to do?": "আপনি কী করতে চান?", "Account type": "অ্যাকাউন্টের ধরন", "Member since": "সদস্য হয়েছেন", "Your student profile": "আপনার শিক্ষার্থী প্রোফাইল", "Your guardian profile": "আপনার অভিভাবক প্রোফাইল", "Your owner profile": "আপনার মালিক প্রোফাইল", "Administration profile": "অ্যাডমিন প্রোফাইল", "Home / Mess Owner": "বাসা / মেস মালিক", "Administrator": "অ্যাডমিন", "Find a suitable home, explore tuition opportunities and connect with the CampusNest community.": "উপযুক্ত বাসা ও টিউশন খুঁজুন এবং CampusNest কমিউনিটির সঙ্গে যুক্ত থাকুন।", "Publish your available rooms or seats and manage interested students from one place.": "খালি রুম বা সিট প্রকাশ করুন এবং আগ্রহী শিক্ষার্থীদের এক জায়গা থেকে পরিচালনা করুন।", "Post tuition requirements and connect with suitable student tutors in your area.": "টিউশনের প্রয়োজন পোস্ট করুন এবং এলাকার উপযুক্ত শিক্ষার্থী শিক্ষকের সঙ্গে যুক্ত হন।", "Manage CampusNest users, listings and community activity.": "CampusNest-এর ব্যবহারকারী, তালিকা ও কমিউনিটি কার্যক্রম পরিচালনা করুন।", "Post tuition": "টিউশন পোস্ট করুন", "Create a new tuition requirement": "নতুন টিউশনের প্রয়োজন পোস্ট করুন", "My tuition posts": "আমার টিউশন পোস্ট", "Manage your active requirements": "সক্রিয় প্রয়োজনগুলো পরিচালনা করুন", "Tutor applications": "শিক্ষকের আবেদন", "Review interested tutor profiles": "আগ্রহী শিক্ষকদের প্রোফাইল দেখুন", "Browse available rooms and mess seats": "খালি রুম ও মেস সিট দেখুন", "Find tuition opportunities near you": "কাছাকাছি টিউশনের সুযোগ খুঁজুন", "Buy or sell": "কিনুন বা বিক্রি করুন", "Trade useful items with students": "শিক্ষার্থীদের সঙ্গে দরকারি জিনিস কেনাবেচা করুন", "Post a listing": "তালিকা পোস্ট করুন", "Add a home, room or available mess seat": "বাসা, রুম বা খালি মেস সিট যোগ করুন", "My listings": "আমার তালিকা", "Review and update your published spaces": "প্রকাশিত জায়গাগুলো দেখুন ও আপডেট করুন", "Student requests": "শিক্ষার্থীদের অনুরোধ", "See students interested in your listings": "আপনার তালিকায় আগ্রহী শিক্ষার্থীদের দেখুন", "Manage users": "ব্যবহারকারী পরিচালনা", "Review registered user accounts": "নিবন্ধিত অ্যাকাউন্ট দেখুন", "Review listings": "তালিকা পর্যালোচনা", "Approve or remove community posts": "কমিউনিটি পোস্ট অনুমোদন বা সরান", "Platform overview": "প্ল্যাটফর্ম সারসংক্ষেপ", "See CampusNest activity at a glance": "CampusNest-এর কার্যক্রম এক নজরে দেখুন",
  "Back to my profile": "আমার প্রোফাইলে ফিরুন", "HOME & MESS": "বাসা ও মেস", "Find a place that feels right.": "পছন্দের ঠিকানা খুঁজে নিন।", "Browse rooms, flats and mess seats shared by CampusNest homeowners.": "CampusNest-এর মালিকদের দেওয়া রুম, ফ্ল্যাট ও মেস সিট দেখুন।", "Search by area or location": "এলাকা বা স্থান দিয়ে খুঁজুন", "Search": "খুঁজুন", "Home listings are coming next": "বাসার তালিকা শিগগিরই আসছে", "This dashboard is ready. Published home and mess listings will appear here.": "Dashboard প্রস্তুত। প্রকাশিত বাসা ও মেসের তালিকা এখানে দেখা যাবে।", "BUY & SELL": "কেনা ও বেচা", "Your campus marketplace.": "আপনার ক্যাম্পাস মার্কেটপ্লেস।", "Discover useful items offered by students in the CampusNest community.": "CampusNest শিক্ষার্থীদের বিক্রির দরকারি জিনিস দেখুন।", "Search campus items": "ক্যাম্পাসের পণ্য খুঁজুন", "Marketplace posts are coming next": "মার্কেটপ্লেস পোস্ট শিগগিরই আসছে", "This dashboard is ready. Products listed by students will appear here.": "Dashboard প্রস্তুত। শিক্ষার্থীদের পণ্য এখানে দেখা যাবে।",
  "Post a tuition requirement.": "টিউশনের প্রয়োজন পোস্ট করুন।", "Tell students what kind of tutor your child needs.": "আপনার সন্তানের কেমন শিক্ষক প্রয়োজন তা জানান।", "Choose the right student tutor.": "সঠিক শিক্ষার্থী শিক্ষক বেছে নিন।", "Review applicants for your tuition posts and select one student.": "আপনার টিউশন পোস্টের আবেদন দেখে একজন শিক্ষার্থী বেছে নিন।", "Manage your tuition posts.": "আপনার টিউশন পোস্ট পরিচালনা করুন।", "See the requirements you have published and their current status.": "আপনার প্রকাশিত প্রয়োজন ও বর্তমান অবস্থা দেখুন।", "Find the right tuition match.": "সঠিক টিউশন খুঁজে নিন।", "Explore tuition opportunities posted by guardians and apply directly.": "অভিভাবকদের টিউশন পোস্ট দেখুন এবং সরাসরি আবেদন করুন।", "NEW REQUIREMENT": "নতুন প্রয়োজন", "Post a tuition": "টিউশন পোস্ট করুন", "Child's class": "সন্তানের শ্রেণি", "Subject": "বিষয়", "Expected teacher department": "প্রত্যাশিত শিক্ষকের বিভাগ", "Offered salary (Tk/month)": "প্রস্তাবিত বেতন (টাকা/মাস)", "Location": "ঠিকানা", "More details": "বিস্তারিত", "Publish tuition requirement": "টিউশনের প্রয়োজন প্রকাশ করুন", "Publishing…": "প্রকাশ করা হচ্ছে…", "Search by class, subject, department or location": "শ্রেণি, বিষয়, বিভাগ বা ঠিকানা দিয়ে খুঁজুন", "AVAILABLE POSTS": "উপলভ্য পোস্ট", "MY TUITION POSTS": "আমার টিউশন পোস্ট", "TUTOR APPLICATIONS": "শিক্ষকের আবেদন", "Loading tuition posts…": "টিউশন পোস্ট লোড হচ্ছে…", "No tuition posts found": "কোনো টিউশন পোস্ট পাওয়া যায়নি", "Guardian tuition requirements will appear here after they are published.": "অভিভাবকের প্রকাশিত টিউশন প্রয়োজন এখানে দেখা যাবে।", "Accepting applications": "আবেদন নেওয়া হচ্ছে", "Student selected": "শিক্ষার্থী নির্বাচিত", "Expected department": "প্রত্যাশিত বিভাগ", "Posted by": "পোস্ট করেছেন", "Apply for this tuition": "এই টিউশনে আবেদন করুন", "Applied": "আবেদন করা হয়েছে", "Applications closed": "আবেদন বন্ধ", "Student applicants": "শিক্ষার্থী আবেদনকারী", "No student has applied yet.": "এখনও কোনো শিক্ষার্থী আবেদন করেনি।", "Select student": "শিক্ষার্থী নির্বাচন করুন", "Selected": "নির্বাচিত",
  "Your tuition requirement is now live.": "আপনার টিউশনের প্রয়োজন প্রকাশিত হয়েছে।", "Application submitted successfully.": "আবেদন সফলভাবে জমা হয়েছে।", "Student selected successfully.": "শিক্ষার্থী সফলভাবে নির্বাচিত হয়েছে।", "You have already applied.": "আপনি ইতিমধ্যে আবেদন করেছেন।", "This tuition is no longer accepting applications.": "এই টিউশনে আর আবেদন নেওয়া হচ্ছে না।", "Email or password is incorrect.": "ইমেইল অথবা পাসওয়ার্ড সঠিক নয়।", "Enter your email address first.": "প্রথমে আপনার ইমেইল ঠিকানা লিখুন।", "Password reset email sent. Check your inbox.": "পাসওয়ার্ড reset email পাঠানো হয়েছে। Inbox দেখুন।",
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("campusnest-language") || "en");
  useEffect(() => { localStorage.setItem("campusnest-language", language); document.documentElement.lang = language === "bn" ? "bn" : "en"; }, [language]);
  const value = useMemo(() => ({ language, setLanguage, t(text, values = {}) { let output = language === "bn" ? (bangla[text] || text) : text; Object.entries(values).forEach(([key, value]) => { output = output.replace(`{${key}}`, value); }); return output; } }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { return useContext(LanguageContext); }
